### ISSUE TITLE
[Character Creation] Add Preview Feature

### ISSUE THREAD

**Issue by systm-spec** [systm-spec/studious-invention#9]
Das Preview ist im Screen der Character-Erstellung der Frame mit dem Bild und einem zweiten Frame fuer die Info Felder.

- [x] erstelle und layoute nach Figma File
- [x] fuege ein Platzhalter-Bild in den Img-Wrapper, das dezent ist und initial auftaucht wenn noch nichts ausgewaehlt wurde
- [x] erstelle und layoute die Info-Boxen (die Boni Boxen unten sind noch nicht fix, ruhig ausprobieren)
- [x] bestuecke die Info Boxen erstmal mit den Texten aus dem Figma, fuer ein gutes Preview
     - [x] Race Info
     - [x] Class Info
     - [x] Boni Box

featured:
- [ ] lass' den gesamten Preview auf einem Buch rendern, damit es so aussieht, als wäre das Bild auf der Linken und die Infoboxen auf der Rechten Seite eines aufgeschlagenen Buches.

**Comment by Ameroras** [comment]
Noch nicht genau wie in Figma. ipady ipady müssen noch eingestellt werden um die Borders einzustellen
